### ISSUE TITLE
where is the Dockerfile of gcr.io/kubeflow/tensorflow-notebook-cpu?

### ISSUE THREAD

**Issue by lgarithm** [google/kubeflow#122]
Where is the Dockerfile of [gcr.io/kubeflow/tensorflow-notebook-cpu](https://github.com/google/kubeflow/blob/master/kubeflow/core/jupyterhub.libsonnet#L49)?

Is it just a mirror of [jupyter/tensorflow-notebook](https://store.docker.com/community/images/jupyter/tensorflow-notebook) defined in https://github.com/jupyter/docker-stacks/tree/master/tensorflow-notebook?

Or is it not open sourced?

**Comment by jlewi** [comment]
The Dockerfiles for the Jupyter notebooks are here
https://github.com/GoogleCloudPlatform/container-engine-accelerators/tree/master/example/tensorflow-notebook-image

(They were in a different repo because the predated the Kubeflow repo).

We should copy them into the Kubeflow repo.

**Comment by jlewi** [comment]
Opened #126

**Comment by dogopupper** [comment]
I made a pull request: https://github.com/kubeflow/kubeflow/pull/182

Let me know if the location should be changed
