### ISSUE TITLE
What's up with Tensorflow?

### ISSUE THREAD

**Issue by IvanAlejandro888** [google/kubeflow#135]
Is there any difference between Tensorflow and Kubeflow? Why are you developing both?

**Comment by jlewi** [comment]
TensorFlow and Kubeflow are very different and very complimentary

TensorFlow is a framework for writing ML algorithms (particular deep learning).

Kubeflow is about making it easy to run TensorFlow and other pieces of an ML platform (e.g. TensorBoard) on Kubernetes.

**Comment by IvanAlejandro888** [comment]
Cool

Jeremy Lewi <notifications@github.com> wrote:



TensorFlow and Kubeflow are very different and very complimentary

TensorFlow is a framework for writing ML algorithms (particular deep learning).

Kubeflow is about making it easy to run TensorFlow and other pieces of an ML platform (e.g. TensorBoard) on Kubernetes.
