### ISSUE TITLE
Syntax error of juypterhub.yaml for Kubernetes

### ISSUE THREAD

**Issue by tobegit3hub** [google/kubeflow#58]
I got the error to validate the `juypterhub.yaml` before starting with the `latest kubeflow` and `Kubernete 1.6`

Here is the error message.

<img width="1440" alt="screen shot 2017-12-21 at 10 18 50 am" src="https://user-images.githubusercontent.com/2715000/34237672-f1683838-e638-11e7-9b84-4f9a463862d0.png">

**Comment by foxish** [comment]
That might be because of K8s 1.6. The template might need to be changed slightly since statefulset didn't support rolling update in 1.6. You could just try removing that section and see. We should use templating for fixing this in future. cc/ @yuvipanda @jlewi

**Comment by jlewi** [comment]
Is there a compelling reason to support Kubernetes 1.6 in Kubeflow?

The TfJob controller requires at least 1.7 for CRDs and 1.8 for GPU support (see [here](https://github.com/tensorflow/k8s)).

We should probably update the docs to reflect this requirement.

**Comment by foxish** [comment]
Fair point - it would make sense to define a support window. The last 2 or 3 releases are typically what we can realistically achieve. Given 1.9 just came out, that still puts us at at least 1.7+ (assuming one doesn't want to use GPUs). Let's document it and close this as WAI.

**Comment by tobegit3hub** [comment]
I'm okay if it works for `Kubernetes 1.7+` and it would be great to add this in introduction.

Thanks for your response @foxish @jlewi
