### ISSUE TITLE
Failed to connect to my Hub at http://tf-hub-0:8081/hub/api (attempt 1/5). Is it running?

### ISSUE THREAD

**Issue by gangliao** [google/kubeflow#78]
![image](https://user-images.githubusercontent.com/3071933/34511061-07b4995a-f094-11e7-834c-83486d9c0ec2.png)

```bash
usermod: no changes
Execute the command as jovyan
[W 2018-01-03 06:36:22.606 SingleUserNotebookApp configurable:168] Config option `open_browser` not recognized by `SingleUserNotebookApp`.  Did you mean `browser`?
/opt/conda/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
[I 2018-01-03 06:36:24.227 SingleUserNotebookApp handlers:46] jupyter_tensorboard extension loaded.
[I 2018-01-03 06:36:24.257 SingleUserNotebookApp extension:38] JupyterLab alpha preview extension loaded from /opt/conda/lib/python3.6/site-packages/jupyterlab
[I 2018-01-03 06:36:24.258 SingleUserNotebookApp extension:88] Running the core application with no additional extensions or settings
[I 2018-01-03 06:36:24.262 SingleUserNotebookApp singleuser:365] Starting jupyterhub-singleuser server version 0.8.1
[I 2018-01-03 06:36:44.287 SingleUserNotebookApp log:122] 302 GET /user/admin/ → /user/admin/tree? (@172.17.0.6) 0.72ms
[I 2018-01-03 06:36:44.288 SingleUserNotebookApp log:122] 302 GET /user/admin/ → /user/admin/tree? (@172.17.0.6) 0.53ms
[E 2018-01-03 06:36:44.288 SingleUserNotebookApp singleuser:354] Failed to connect to my Hub at http://tf-hub-0:8081/hub/api (attempt 1/5). Is it running?
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 351, in check_hub_version
```

**Comment by jlewi** [comment]
What URL are you accessing Jupyter at?

How are you connecting to Jupyter on your cluster? Are you exposing Jupyter Hub on an external IP? Are you connecting using kubectl port-forward?

The url `http://tf-hub-0:8081` looks suspect. `tf-hub-0` is the name of the JupyterHub pod and service; if you're outside the cluster those won't map to valid hostnames. However, the fact that this is returning a 500 though and not a 400, I think indicates the name is being mapped to an IP.

Were you able to reach the Jupyter login page?

Did you try connecting via `kubectl port-forward`

```
kubectl port-forward tf-hub-0 8100:8000
```
And then accessing `http://localhost:8100`?

/cc @yuvipanda @foxish

**Comment by harryliu123** [comment]
i have same case 
i thank question is not registered tf-hub-0 on kube-dns

root@XXXX:~# kubectl exec busybox -- nslookup tf-hub-0
Server:    10.96.0.10
Address 1: 10.96.0.10 kube-dns.kube-system.svc.cluster.local

nslookup: can't resolve 'tf-hub-0'
command terminated with exit code 1

**Comment by foxish** [comment]
`http://tf-hub-0:8081` should be an in-cluster resolvable DNS name that the jupyter notebooks pods use to connect back to the hub.
Can you verify that the headless service has been created, and that kube-dns is enabled?

**Comment by gangliao** [comment]
Yes, the problem is from kube-dns, after it was reconfigured, kubeflow works well. Thank you! @foxish

**Comment by jlewi** [comment]
@gangliao For posterity, what did you have to do to reconfigure kube-dns? Also how are you running Kubernetes?

**Comment by gangliao** [comment]
@jlewi  My case is quite special. I find  Flannel is configured incorrectly, then I reconfigure it and also restart my kube-dns, finally `http://tf-hub-0:8081` can be resolved.

**Comment by jlewi** [comment]
Thanks.
