### ISSUE TITLE
if i use kubeflow on local cluster with gpu

### ISSUE THREAD

**Issue by GoodJoey** [google/kubeflow#79]
do i need to add the nvidia driver map manually?
as i didn't see any introduction about map the nvidia driver in the guide, a little confuse about that.

**Comment by pineking** [comment]
see doc: https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/
the driver libs path can be removed from YAML file, if you use nvidia-docker 2.0 together with device plugin.

**Comment by GoodJoey** [comment]
thanks, help a lot.
