### ISSUE TITLE
Delete inception.tar.gz

### ISSUE THREAD

**Issue by jlewi** [google/kubeflow#98]
We have a copy of inception checked into the repo 
[here](https://github.com/google/kubeflow/blob/master/components/k8s-model-server/inception.tar.gz).

I don't recall why we checked it into the repo. I think we already host a public copy on GCS for use in our samples. 

We should remove it from the repo; its just unnecessary bloat.

**Comment by gaocegege** [comment]
The issue is solved by #111 and I think we could close it 😄
